=== NGI-TRUSTCHAIN/CreatorCredentials/specifications/json-schema/verification-credentials/wallet/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Creator Credentials - Verifiable Wallet Address",
  "description": "Verifiable wallet address credential",
  "type": "object",
  "properties": {
    "@context": {
      "description": "Semantic context for the issued credential. First element MUST be https://www.w3.org/ns/credentials/v2",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      },
      "contains": {
        "const": "https://www.w3.org/ns/credentials/v2"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "id": {
      "description": "Globally unique identifier for the issued credential. It can be a UUID or another globally unique identifier.",
      "type": "string",
      "format": "uri"
    },
    "type": {
      "description": "Full type chain, used to identify the credential base types",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "issuer": {
      "description": "DID of the credential issuer",
      "oneOf": [
        {
          "type": "string",
          "format": "uri"
        },
        {
          "type": "object",
          "required": ["id"],
          "properties": {
            "id": {
              "description": "DID of the credential issuer",
              "type": "string",
              "format": "uri"
            }
          }
        }
      ]
    },
    "validFrom": {
      "description": "Defines the earliest point when the credential becomes valid.",
      "type": "string",
      "format": "date-time"
    },
    "validUntil": {
      "description": "Defines the latest point when the credential ceases to be valid.",
      "type": "string",
      "format": "date-time"
    },
    "credentialSubject": {
      "anyOf": [
        {
          "$ref": "#/$defs/credentialSubject"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/credentialSubject"
          }
        }
      ]
    },
    "credentialStatus": {
      "description": "Defines suspension and/or revocation details for the issued credential. Further redefined by the type extension",
      "type": "object",
      "properties": {
        "id": {
          "description": "Exact identity for the credential status",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines the revocation type extension",
          "type": "string"
        }
      },
      "required": ["id", "type"]
    },
    "credentialSchema": {
      "description": "One or more schemas that validate the Verifiable Credential.",
      "anyOf": [
        {
          "$ref": "#/$defs/credentialSchema"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/credentialSchema"
          }
        }
      ]
    },
    "termsOfUse": {
      "anyOf": [
        {
          "$ref": "#/$defs/termsOfUse"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/termsOfUse"
          }
        }
      ]
    },
    "evidence": {
      "anyOf": [
        {
          "$ref": "#/$defs/evidence"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/evidence"
          }
        }
      ]
    },
    "relatedResource": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "URL the integrity information is for",
            "type": "string",
            "format": "uri"
          },
          "mediaType": {
            "description": "Expected media type for the indicated resource",
            "type": "string"
          }
        },
        "required": ["id"],
        "anyOf": [
          {
            "properties": {
              "digestSRI": {
                "description": "Digest value of Subresource Integrity",
                "type": "string"
              }
            },
            "required": ["digestSRI"]
          },
          {
            "properties": {
              "digestMultibase": {
                "description": "Digest value of multihash encoded in multibase.",
                "type": "string"
              }
            },
            "required": ["digestMultibase"]
          }
        ]
      }
    }
  },
  "required": [
    "@context",
    "id",
    "type",
    "issuer",
    "validFrom",
    "credentialSubject",
    "credentialSchema"
  ],
  "$defs": {
    "credentialSubject": {
      "description": "Defines information about the subject that is defined by the type chain",
      "type": "object",
      "properties": {
        "id": {
          "description": "Defines the DID of the subject that is described by the issued credential",
          "type": "string",
          "format": "uri"
        },
        "address": {
          "description": "Defines the Ethereum address of the credential subject",
          "type": "string"
        }
      }
    },
    "credentialSchema": {
      "description": "Contains information about the credential schema on which the issued credential is based",
      "type": "object",
      "properties": {
        "id": {
          "description": "References the verifiable credential schema",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines credential schema type",
          "type": "string",
          "enum": ["JsonSchema", "ShaclValidator2017"]
        }
      },
      "required": ["id", "type"]
    },
    "termsOfUse": {
      "description": "Contains the terms under which the issued credential was issued",
      "type": "object",
      "properties": {
        "id": {
          "description": "Contains a URL that points to where more information about this instance of terms of use can be found.",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines the type extension",
          "type": "string"
        }
      },
      "required": ["type"]
    },
    "evidence": {
      "type": "object",
      "properties": {
        "id": {
          "description": "If present, it MUST contain a URL that points to where more information about this instance of evidence can be found.",
          "type": "string"
        },
        "type": {
          "anyOf": [
            {
              "description": "Defines the evidence type extension",
              "type": "string"
            },
            {
              "description": "Defines the evidence type extension",
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        }
      },
      "required": ["type"]
    }
  }
}

=== NGI-TRUSTCHAIN/CreatorCredentials/specifications/json-schema/verification-credentials/wallet/example.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "id": "urn:uuid:003a1dd8-a5d2-42ef-8182-e921c0a9f2cd",
  "type": [
    "VerifiableCredential",
    "VerifiableAttestation",
    "VerifiableEthereumAddress"
  ],
  "issuer": "did:web:creatorcredentials.dev",
  "validFrom": "2023-01-01T00:00:00Z",
  "validUntil": "2025-01-01T00:00:00Z",
  "credentialSubject": {
    "id": "did:web:wonderland.com#0",
    "address": "0x0000000000000000000000000000000000000000"
  },
  "credentialSchema": [
    {
      "id": "https://github.com/creatorcredentials/schemas/address.json",
      "type": "JsonSchema"
    }
  ]
}

=== NGI-TRUSTCHAIN/CreatorCredentials/specifications/json-schema/verification-credentials/domain-name/example.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "id": "urn:uuid:003a1dd8-a5d2-42ef-8182-e921c0a9f2cd",
  "type": [
    "VerifiableCredential",
    "VerifiableAttestation",
    "VerifiableDomainName"
  ],
  "issuer": "did:web:creatorcredentials.dev",
  "validFrom": "2023-01-01T00:00:00Z",
  "validUntil": "2025-01-01T00:00:00Z",
  "credentialSubject": {
    "id": "did:web:wonderland.com#0",
    "domainName": "wonderland.com"
  },
  "credentialSchema": [
    {
      "id": "https://github.com/creatorcredentials/schemas/domainName.json",
      "type": "JsonSchema"
    }
  ]
}

=== NGI-TRUSTCHAIN/CreatorCredentials/specifications/json-schema/verification-credentials/email/example.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "id": "urn:uuid:003a1dd8-a5d2-42ef-8182-e921c0a9f2cd",
  "type": [
    "VerifiableCredential",
    "VerifiableAttestation",
    "VerifiableEmail"
  ],
  "issuer": "did:web:host.com",
  "validFrom": "2023-01-01T00:00:00Z",
  "validUntil": "2025-01-01T00:00:00Z",
  "credentialSubject": {
    "id": "did:key:alice...#0",
    "email": "alice@wonderland.com"
  },
  "credentialSchema": [
    {
      "id": "https://github.com/creatorcredentials/schemas/email.json",
      "type": "JsonSchema"
    }
  ],
  "termsOfUse": {
    "type": "PresentationPolicy",
    "confidentialityLevel": "restricted",
    "pii": "sensitive"
  }
}
